use std::io::{stdout, Write};
use bindings::region::{ErrorContext, RemoteModule, SubscriptionEventContext};
use spacetimedb_sdk::{DbContext, Error, __codegen::SubscriptionBuilder};

pub trait ResourceSubscription {
    fn all_resources(self, on_error: fn(&ErrorContext, Error), on_applied: fn(&SubscriptionEventContext));

    fn next_resource(self, n: usize, on_error: fn(&ErrorContext, Error), on_applied: fn(&SubscriptionEventContext));
}

impl ResourceSubscription for SubscriptionBuilder<RemoteModule> {
    fn all_resources(self, on_error: fn(&ErrorContext, Error), on_applied: fn(&SubscriptionEventContext)) {
        self.next_resource(0, on_error, on_applied);
    }

    fn next_resource(self, n: usize, on_error: fn(&ErrorContext, Error), on_applied: fn(&SubscriptionEventContext)) {
        if n == 0 {
            // beginning of subscription cycle
            println!("subscribing:");
            print!("  tier {:>2} ", ALL[n].tier);
        } else if ALL[n].tier != ALL[n - 1].tier {
            // end of tier, next tier starting
            println!("!");
            print!("  tier {:>2} ", ALL[n].tier);
        } else {
            // mid tier
            print!(".");
        }
        stdout().flush().unwrap();

        let res = ALL[n].id;
        self.on_error(on_error)
            .on_applied(move |ctx| {
                if n + 1 == ALL.len() {
                    println!("!");
                    stdout().flush().unwrap();
                    on_applied(ctx);
                } else {
                    ctx.subscription_builder()
                        .next_resource(n + 1, on_error, on_applied);
                }
            })
            .subscribe([
                format!("SELECT res.* FROM resource_state res JOIN location_state loc ON res.entity_id = loc.entity_id WHERE res.resource_id = {};", res),
                format!("SELECT loc.* FROM location_state loc JOIN resource_state res ON loc.entity_id = res.entity_id WHERE res.resource_id = {};", res),
            ]);
    }
}

struct Resource { tier: u8, id: i32, name: &'static str }

const ALL: [Resource; 433] = [
    Resource { tier: 10, id:         102, name: "White Lily"                                 },
    Resource { tier: 10, id:    70663203, name: "Tier 10 Boulder"                            },
    Resource { tier: 10, id:    93152192, name: "Flawless Hieroglyphs"                       },
    Resource { tier: 10, id:   370078223, name: "Astralite Outcrop Interior"                 },
    Resource { tier: 10, id:   374159821, name: "School Of Flawless Lakefish"                },
    Resource { tier: 10, id:   424796674, name: "School Of Flawless Ocean Fish"              },
    Resource { tier: 10, id:   473828668, name: "Bamboo"                                     },
    Resource { tier: 10, id:   939382648, name: "Wisteria Tree"                              },
    Resource { tier: 10, id:  1006230316, name: "Frenzied School Of Flawless Ocean Fish"     },
    Resource { tier: 10, id:  1023127595, name: "Flawless Clay"                              },
    Resource { tier: 10, id:  1159270109, name: "Tier 10 Tree"                               },
    Resource { tier: 10, id:  1283711960, name: "Flawless Baitfish"                          },
    Resource { tier: 10, id:  1333270269, name: "Flawless Sand"                              },
    Resource { tier: 10, id:  1357154092, name: "Astralite Vein Interior Depleted"           },
    Resource { tier: 10, id:  1444297495, name: "Medium Astralite Vein Interior Depleted"    },
    Resource { tier: 10, id:  1452484871, name: "Medium Astralite Vein Interior"             },
    Resource { tier: 10, id:  1467799531, name: "Dewberry Bush"                              },
    Resource { tier: 10, id:  1489491467, name: "Tier 10 Fibers"                             },
    Resource { tier: 10, id:  1526350171, name: "Astralite Outcrop Interior Depleted"        },
    Resource { tier: 10, id:  1606770008, name: "Astralite Vein"                             },
    Resource { tier: 10, id:  1637125903, name: "Flawless Mushroom"                          },
    Resource { tier: 10, id:  1747556974, name: "Astralite Vein Interior"                    },
    Resource { tier: 10, id:  1986100626, name: "Tier 10 Flower"                             },
    Resource { tier: 10, id:  1996631377, name: "Tier 10 Outcrop"                            },
    Resource { tier: 10, id:  2089197796, name: "Enoki"                                      },
    Resource { tier: 10, id:  2110330714, name: "Flawless Berry Bush"                        },
    Resource { tier:  9, id:          83, name: "King Trumpet"                               },
    Resource { tier:  9, id:          86, name: "Citriformis"                                },
    Resource { tier:  9, id:    20400246, name: "Umbracite Vein Interior Depleted"           },
    Resource { tier:  9, id:    64125498, name: "Umbracite Vein Interior"                    },
    Resource { tier:  9, id:   189403270, name: "Tier 9 Fibers"                              },
    Resource { tier:  9, id:   284200468, name: "Tier 9 Flower"                              },
    Resource { tier:  9, id:   331687458, name: "Magnificient Hieroglyphs"                   },
    Resource { tier:  9, id:   562432497, name: "Magnificient Sand"                          },
    Resource { tier:  9, id:   749656892, name: "Medium Umbracite Vein Interior Depleted"    },
    Resource { tier:  9, id:   756579517, name: "Magnificient Baitfish"                      },
    Resource { tier:  9, id:   814703516, name: "Umbracite Outcrop Interior"                 },
    Resource { tier:  9, id:   939701809, name: "Gigantic Sapwood Tree"                      },
    Resource { tier:  9, id:   963451338, name: "Magnificient Berry Bush"                    },
    Resource { tier:  9, id:  1113640469, name: "Tier 9 Outcrop"                             },
    Resource { tier:  9, id:  1141184831, name: "Frenzied School Of Magnificient Ocean Fish" },
    Resource { tier:  9, id:  1157887989, name: "School Of Magnificient Lake Fish"           },
    Resource { tier:  9, id:  1241355606, name: "Umbracite Outcrop Interior Depleted"        },
    Resource { tier:  9, id:  1384946093, name: "Medium Umbracite Vein Interior"             },
    Resource { tier:  9, id:  1386735112, name: "Umbracite Vein"                             },
    Resource { tier:  9, id:  1458811602, name: "Seaweed"                                    },
    Resource { tier:  9, id:  1526038154, name: "Magnificient Clay"                          },
    Resource { tier:  9, id:  1574437474, name: "Sapwood Tree"                               },
    Resource { tier:  9, id:  1742959882, name: "Magnificient Mushroom"                      },
    Resource { tier:  9, id:  1812221896, name: "School Of Magnificient Ocean Fish"          },
    Resource { tier:  9, id:  1821415333, name: "Mature Sapwood Tree"                        },
    Resource { tier:  9, id:  1902966974, name: "Tier 9 Boulder"                             },
    Resource { tier:  9, id:  1954847232, name: "Black Fig Bush"                             },
    Resource { tier:  8, id:          84, name: "Cloudberry Bush"                            },
    Resource { tier:  8, id:          85, name: "Ghost Mushroom"                             },
    Resource { tier:  8, id:         105, name: "King of the Alps"                           },
    Resource { tier:  8, id:         137, name: "Arctic Grass"                               },
    Resource { tier:  8, id:     2390533, name: "School Of Mysterious Anglerfish"            },
    Resource { tier:  8, id:    20857160, name: "Celestium Outcrop Interior"                 },
    Resource { tier:  8, id:    71559749, name: "Celestium Vein Interior Depleted"           },
    Resource { tier:  8, id:   457752715, name: "Pristine Sand"                              },
    Resource { tier:  8, id:   479638263, name: "Tier 8 Boulder"                             },
    Resource { tier:  8, id:   505488132, name: "Pristine Clay"                              },
    Resource { tier:  8, id:   509854054, name: "Frenzied School Of Mysterious Anglerfish"   },
    Resource { tier:  8, id:   650019671, name: "Medium Celestium Vein Interior Depleted"    },
    Resource { tier:  8, id:   722506673, name: "School Of Rainbowscaled Tilapia"            },
    Resource { tier:  8, id:  1101060328, name: "Ficus Tree"                                 },
    Resource { tier:  8, id:  1125409070, name: "Tier 8 Fibers"                              },
    Resource { tier:  8, id:  1162923141, name: "Celestium Vein Interior"                    },
    Resource { tier:  8, id:  1264935363, name: "Tier 8 Flower"                              },
    Resource { tier:  8, id:  1332797261, name: "Celestium Vein"                             },
    Resource { tier:  8, id:  1423928615, name: "Tier 8 Outcrop"                             },
    Resource { tier:  8, id:  1558728865, name: "Sparkling Prawn"                            },
    Resource { tier:  8, id:  1567694896, name: "Pristine Hieroglyphs"                       },
    Resource { tier:  8, id:  1592739620, name: "Pristine Berry Bush"                        },
    Resource { tier:  8, id:  1657885116, name: "Pristine Mushroom"                          },
    Resource { tier:  8, id:  1731709368, name: "Overwhelming Hexite Energy Font"            },
    Resource { tier:  8, id:  2025189123, name: "Medium Celestium Vein Interior"             },
    Resource { tier:  8, id:  2140754992, name: "Celestium Outcrop Interior Depleted"        },
    Resource { tier:  7, id:          35, name: "Young Baobab Tree"                          },
    Resource { tier:  7, id:          36, name: "Ancient Baobab Tree"                        },
    Resource { tier:  7, id:          76, name: "Oyster Mushrooms"                           },
    Resource { tier:  7, id:         104, name: "Golden Witlow"                              },
    Resource { tier:  7, id:         128, name: "Grassy Reeds"                               },
    Resource { tier:  7, id:         129, name: "Reindeer Lichen"                            },
    Resource { tier:  7, id:     5045122, name: "School Of Tidebreaker Barracuda"            },
    Resource { tier:  7, id:   139483458, name: "Aurumite Vein"                              },
    Resource { tier:  7, id:   387666932, name: "Tier 7 Tree"                                },
    Resource { tier:  7, id:   411376268, name: "Aurumite Vein Interior Depleted"            },
    Resource { tier:  7, id:   582591086, name: "Ornate Berry Bush"                          },
    Resource { tier:  7, id:   586543849, name: "Ornate Mushroom"                            },
    Resource { tier:  7, id:   723013812, name: "Tier 7 Flower"                              },
    Resource { tier:  7, id:   826362353, name: "Frenzied School Of Tidebreaker Barracuda"   },
    Resource { tier:  7, id:   834195042, name: "Ornate Clay"                                },
    Resource { tier:  7, id:   904022325, name: "School Of Speedy Glowfin"                   },
    Resource { tier:  7, id:  1171246287, name: "Medium Aurumite Vein Interior Depleted"     },
    Resource { tier:  7, id:  1262898141, name: "Misty Crustacean"                           },
    Resource { tier:  7, id:  1332535555, name: "Ornate Sand"                                },
    Resource { tier:  7, id:  1440062914, name: "Tier 7 Boulder"                             },
    Resource { tier:  7, id:  1579330042, name: "Yellow Apricot Bush"                        },
    Resource { tier:  7, id:  1689263994, name: "Aurumite Outcrop Interior Depleted"         },
    Resource { tier:  7, id:  1800013378, name: "Medium Aurumite Vein Interior"              },
    Resource { tier:  7, id:  1981854097, name: "Tier 7 Fibers"                              },
    Resource { tier:  7, id:  2031243337, name: "Aurumite Vein Interior"                     },
    Resource { tier:  7, id:  2073862342, name: "Aurumite Outcrop Interior"                  },
    Resource { tier:  7, id:  2104975743, name: "Tier 7 Outcrop"                             },
    Resource { tier:  7, id:  2124845482, name: "Ornate Hieroglyphs"                         },
    Resource { tier:  6, id:           5, name: "Maple Sapling"                              },
    Resource { tier:  6, id:          17, name: "Young Maple Tree"                           },
    Resource { tier:  6, id:          23, name: "Ancient Oak Tree"                           },
    Resource { tier:  6, id:          24, name: "Gnarled Maple Tree"                         },
    Resource { tier:  6, id:          25, name: "Mature Maple Tree"                          },
    Resource { tier:  6, id:          56, name: "Marble Outcrop"                             },
    Resource { tier:  6, id:          57, name: "Marble Boulder"                             },
    Resource { tier:  6, id:          65, name: "Rathium Vein"                               },
    Resource { tier:  6, id:          71, name: "Bentonite Clay"                             },
    Resource { tier:  6, id:          81, name: "Morel Mushrooms"                            },
    Resource { tier:  6, id:          99, name: "Desert Rose"                                },
    Resource { tier:  6, id:         101, name: "Fireweed"                                   },
    Resource { tier:  6, id:         139, name: "Ancient Thorns"                             },
    Resource { tier:  6, id:         145, name: "Peerless Hieroglyphs"                       },
    Resource { tier:  6, id:         201, name: "Energy Source"                              },
    Resource { tier:  6, id:         202, name: "Ornate Key Pedestal"                        },
    Resource { tier:  6, id:         203, name: "Advanced Key Pedestal"                      },
    Resource { tier:  6, id:         204, name: "Power Source"                               },
    Resource { tier:  6, id:         205, name: "Broken Power Source"                        },
    Resource { tier:  6, id:         206, name: "Collapsed Marble Pillars"                   },
    Resource { tier:  6, id:         207, name: "Advanced Door"                              },
    Resource { tier:  6, id:         208, name: "Right Power Core Pedestal"                  },
    Resource { tier:  6, id:         209, name: "Empty Power Core Pedestal"                  },
    Resource { tier:  6, id:         210, name: "Runic Door"                                 },
    Resource { tier:  6, id:         211, name: "Trap Rubble"                                },
    Resource { tier:  6, id:         212, name: "Runic Door "                                },
    Resource { tier:  6, id:         213, name: "Mysterious Contraption"                     },
    Resource { tier:  6, id:         214, name: "Powered Contraption"                        },
    Resource { tier:  6, id:         223, name: "Left Power Core Pedestal"                   },
    Resource { tier:  6, id:     3010008, name: "Planted Maple Sapling"                      },
    Resource { tier:  6, id:     3011008, name: "Planted Maple Tree"                         },
    Resource { tier:  6, id:     3012008, name: "Fully Grown Maple Tree"                     },
    Resource { tier:  6, id:     6110000, name: "Sunrise Shrimp"                             },
    Resource { tier:  6, id:     6110001, name: "School Of Hexfin Perch"                     },
    Resource { tier:  6, id:     6110002, name: "School Of Abyssal Swordfish"                },
    Resource { tier:  6, id:     6110003, name: "Frenzied School Of Abyssal Swordfish"       },
    Resource { tier:  6, id:     6110004, name: "Abyssal Oyster"                             },
    Resource { tier:  6, id:   246146358, name: "Rathium Vein Interior Depleted"             },
    Resource { tier:  6, id:   368570220, name: "Cranberry Bush"                             },
    Resource { tier:  6, id:   702104027, name: "Clay Termite Mound"                         },
    Resource { tier:  6, id:   750444302, name: "Medium Rathium Vein Interior Depleted"      },
    Resource { tier:  6, id:   762731569, name: "Palmetto"                                   },
    Resource { tier:  6, id:   773149133, name: "Medium Rathium Vein Interior"               },
    Resource { tier:  6, id:   875245395, name: "Mistberry Bush"                             },
    Resource { tier:  6, id:   916586661, name: "Rathium Outcrop Interior"                   },
    Resource { tier:  6, id:   932989637, name: "Powerful Hexite Energy Font"                },
    Resource { tier:  6, id:   999376882, name: "Desert Sand"                                },
    Resource { tier:  6, id:  1318826480, name: "Rathium Outcrop Interior Depleted"          },
    Resource { tier:  6, id:  2027405944, name: "Rathium Vein Interior"                      },
    Resource { tier:  5, id:          30, name: "Stunted Cypress Tree"                       },
    Resource { tier:  5, id:          31, name: "Dead Cypress Tree"                          },
    Resource { tier:  5, id:          33, name: "Mature Cypress Tree"                        },
    Resource { tier:  5, id:          34, name: "Ancient Cypress Tree"                       },
    Resource { tier:  5, id:          54, name: "Diorite Outcrop"                            },
    Resource { tier:  5, id:          55, name: "Diorite Boulder"                            },
    Resource { tier:  5, id:          64, name: "Luminite Vein"                              },
    Resource { tier:  5, id:          70, name: "Kaolinite Clay"                             },
    Resource { tier:  5, id:          75, name: "Blackberry Bush"                            },
    Resource { tier:  5, id:          82, name: "Truffle Patch"                              },
    Resource { tier:  5, id:          98, name: "Morning Glory"                              },
    Resource { tier:  5, id:         103, name: "Ghost Thyme"                                },
    Resource { tier:  5, id:         135, name: "Heather"                                    },
    Resource { tier:  5, id:         136, name: "Large Brambles"                             },
    Resource { tier:  5, id:         138, name: "Pink Lilies"                                },
    Resource { tier:  5, id:         144, name: "Exquisite Hieroglyphs"                      },
    Resource { tier:  5, id:     4011011, name: "Planted Cypress Tree"                       },
    Resource { tier:  5, id:     4012011, name: "Fully Grown Cypress Tree"                   },
    Resource { tier:  5, id:     5050000, name: "Garden Pillar Interior"                     },
    Resource { tier:  5, id:     5050001, name: "Garden Formation Interior"                  },
    Resource { tier:  5, id:     5050002, name: "Diorite Pillar Interior"                    },
    Resource { tier:  5, id:     5110000, name: "Golden Crawfish"                            },
    Resource { tier:  5, id:     5110001, name: "School Of Emberscale Sturgeon"              },
    Resource { tier:  5, id:     5110002, name: "School Of Azure Sharks"                     },
    Resource { tier:  5, id:     5110003, name: "Frenzied School Of Azure Sharks"            },
    Resource { tier:  5, id:     5110004, name: "Armored Reef Clam"                          },
    Resource { tier:  5, id:    49710228, name: "Luminite Outcrop Interior Depleted"         },
    Resource { tier:  5, id:   549538391, name: "Medium Luminite Vein Interior"              },
    Resource { tier:  5, id:   642972236, name: "Luminite Outcrop Interior"                  },
    Resource { tier:  5, id:   887736443, name: "Luminite Vein Interior"                     },
    Resource { tier:  5, id:  1005142992, name: "Elephant Fibers"                            },
    Resource { tier:  5, id:  1126774401, name: "Medium Luminite Vein Interior Depleted"     },
    Resource { tier:  5, id:  1365934955, name: "Luminite Vein Interior Depleted"            },
    Resource { tier:  5, id:  1691492474, name: "Coral Sand"                                 },
    Resource { tier:  4, id:          16, name: "Young Pine Tree"                            },
    Resource { tier:  4, id:          26, name: "Mature Pine Tree"                           },
    Resource { tier:  4, id:          32, name: "Ancient Pine Tree"                          },
    Resource { tier:  4, id:          52, name: "Basalt Outcrop"                             },
    Resource { tier:  4, id:          53, name: "Basalt Stalagmite"                          },
    Resource { tier:  4, id:          63, name: "Elenvar Vein"                               },
    Resource { tier:  4, id:          69, name: "Fine Clay"                                  },
    Resource { tier:  4, id:          92, name: "Bluebell"                                   },
    Resource { tier:  4, id:         100, name: "Rosemary"                                   },
    Resource { tier:  4, id:         133, name: "Thorny Stump"                               },
    Resource { tier:  4, id:         134, name: "Brambles"                                   },
    Resource { tier:  4, id:         143, name: "Fine Hieroglyphs"                           },
    Resource { tier:  4, id:     2050000, name: "Garden Boulder"                             },
    Resource { tier:  4, id:     3011009, name: "Planted Pine Tree"                          },
    Resource { tier:  4, id:     3012009, name: "Fully Grown Pine Tree"                      },
    Resource { tier:  4, id:     4050000, name: "Garden Pillar"                              },
    Resource { tier:  4, id:     4050001, name: "Garden Formation"                           },
    Resource { tier:  4, id:     4050002, name: "Rocky Garden Pillar"                        },
    Resource { tier:  4, id:     4050003, name: "Rocky Garden Pillars"                       },
    Resource { tier:  4, id:     4050004, name: "Rocky Garden Formation"                     },
    Resource { tier:  4, id:     4050005, name: "Diorite Pillar"                             },
    Resource { tier:  4, id:     4050006, name: "Large Rocky Garden Pillars"                 },
    Resource { tier:  4, id:     4050007, name: "Large Rocky Garden Formations"              },
    Resource { tier:  4, id:     4110000, name: "Pygmy Lobsters"                             },
    Resource { tier:  4, id:     4110001, name: "School Of Mossfin Chub"                     },
    Resource { tier:  4, id:     4110002, name: "School Of Seastorm Tuna"                    },
    Resource { tier:  4, id:     4110003, name: "Frenzied School Of Seastorm Tuna"           },
    Resource { tier:  4, id:     4110004, name: "Crystal Shell Scallop"                      },
    Resource { tier:  4, id:   205387239, name: "Medium Elenvar Vein Interior Depleted"      },
    Resource { tier:  4, id:   532077242, name: "Indigo Milk Cap"                            },
    Resource { tier:  4, id:   541862086, name: "Garnet Sand"                                },
    Resource { tier:  4, id:   715451185, name: "Blueberry Bush"                             },
    Resource { tier:  4, id:   782933576, name: "Elenvar Outcrop Interior"                   },
    Resource { tier:  4, id:   789563787, name: "Strong Hexite Energy Font"                  },
    Resource { tier:  4, id:   806722041, name: "Elenvar Vein Interior Depleted"             },
    Resource { tier:  4, id:  1077990023, name: "Elenvar Vein Interior"                      },
    Resource { tier:  4, id:  1566846336, name: "Rosewood Tree"                              },
    Resource { tier:  4, id:  1709170104, name: "Elenvar Outcrop Interior Depleted"          },
    Resource { tier:  4, id:  1917261269, name: "Jute"                                       },
    Resource { tier:  4, id:  2066552867, name: "Medium Elenvar Vein Interior"               },
    Resource { tier:  3, id:          15, name: "Young Spruce Tree"                          },
    Resource { tier:  3, id:          22, name: "Large Stump"                                },
    Resource { tier:  3, id:          27, name: "Mature Spruce Tree"                         },
    Resource { tier:  3, id:          28, name: "Large Fallen Tree"                          },
    Resource { tier:  3, id:          50, name: "Granite Boulder"                            },
    Resource { tier:  3, id:          51, name: "Granite Outcrop"                            },
    Resource { tier:  3, id:          62, name: "Emarium Vein"                               },
    Resource { tier:  3, id:          68, name: "Earthenware Clay"                           },
    Resource { tier:  3, id:          78, name: "Juniper Berry Bush"                         },
    Resource { tier:  3, id:          93, name: "Aloe"                                       },
    Resource { tier:  3, id:          95, name: "Snowdrop Flowers"                           },
    Resource { tier:  3, id:          96, name: "Marigold"                                   },
    Resource { tier:  3, id:          97, name: "Thyme"                                      },
    Resource { tier:  3, id:         130, name: "Ghost Succulent"                            },
    Resource { tier:  3, id:         131, name: "Bullrushes"                                 },
    Resource { tier:  3, id:         132, name: "Spanish Moss"                               },
    Resource { tier:  3, id:         142, name: "Neat Hieroglyphs"                           },
    Resource { tier:  3, id:         153, name: "Fossils"                                    },
    Resource { tier:  3, id:         154, name: "Sandcovered Fossils"                        },
    Resource { tier:  3, id:         215, name: "Vines T3"                                   },
    Resource { tier:  3, id:         216, name: "Root T3"                                    },
    Resource { tier:  3, id:         217, name: "Rubble T3"                                  },
    Resource { tier:  3, id:         218, name: "Enadarite Stand"                            },
    Resource { tier:  3, id:         219, name: "Key Mold Pedestal"                          },
    Resource { tier:  3, id:         220, name: "Empty Enadarite Stand"                      },
    Resource { tier:  3, id:         221, name: "Empty Key Mold Pedestal"                    },
    Resource { tier:  3, id:         222, name: "Enadarite Door"                             },
    Resource { tier:  3, id:     1000028, name: "Large Fallen Tree Stump"                    },
    Resource { tier:  3, id:     1000029, name: "Fallen Grove Tree"                          },
    Resource { tier:  3, id:     3011010, name: "Planted Spruce Tree"                        },
    Resource { tier:  3, id:     3011011, name: "Planted Willow Tree"                        },
    Resource { tier:  3, id:     3012010, name: "Fully Grown Spruce Tree"                    },
    Resource { tier:  3, id:     3012011, name: "Fully Grown Willow Tree"                    },
    Resource { tier:  3, id:     3020001, name: "Medium Emarium Vein"                        },
    Resource { tier:  3, id:     3020002, name: "Large Emarium Vein"                         },
    Resource { tier:  3, id:     3110000, name: "Hunchback Prawns"                           },
    Resource { tier:  3, id:     3110001, name: "School Of Coralcrest Darter"                },
    Resource { tier:  3, id:     3110002, name: "School Of Wavecrest Eels"                   },
    Resource { tier:  3, id:     3110003, name: "Frenzied School Of Wavecrest Eels"          },
    Resource { tier:  3, id:     3110004, name: "Pearlback Snail"                            },
    Resource { tier:  3, id:   198759779, name: "Emarium Outcrop Interior"                   },
    Resource { tier:  3, id:   379219978, name: "Medium Emarium Vein Interior"               },
    Resource { tier:  3, id:   986344159, name: "Medium Emarium Vein Interior Depleted"      },
    Resource { tier:  3, id:  1064484466, name: "Emarium Outcrop Interior Depleted"          },
    Resource { tier:  3, id:  1072537375, name: "Russala"                                    },
    Resource { tier:  3, id:  1180909566, name: "Crystalized Sand"                           },
    Resource { tier:  3, id:  1908426535, name: "Windswept Tree"                             },
    Resource { tier:  3, id:  2068688558, name: "Emarium Vein Interior Depleted"             },
    Resource { tier:  3, id:  2072988001, name: "Emarium Vein Interior"                      },
    Resource { tier:  2, id:           9, name: "Birch Sapling"                              },
    Resource { tier:  2, id:          13, name: "Young Birch Tree"                           },
    Resource { tier:  2, id:          18, name: "Dendro Tree"                                },
    Resource { tier:  2, id:          20, name: "Mature Birch Tree"                          },
    Resource { tier:  2, id:          29, name: "Large Tree Stump"                           },
    Resource { tier:  2, id:          46, name: "Shale Boulder"                              },
    Resource { tier:  2, id:          47, name: "Shale Outcrop"                              },
    Resource { tier:  2, id:          48, name: "Sandstone Boulder"                          },
    Resource { tier:  2, id:          49, name: "Sandstone Outcrop"                          },
    Resource { tier:  2, id:          61, name: "Pyrelite Vein"                              },
    Resource { tier:  2, id:          67, name: "Clay Mound"                                 },
    Resource { tier:  2, id:          77, name: "Prickly Pear"                               },
    Resource { tier:  2, id:          79, name: "Chanterelles"                               },
    Resource { tier:  2, id:          80, name: "Honeyberry Bush"                            },
    Resource { tier:  2, id:          87, name: "Dandelions"                                 },
    Resource { tier:  2, id:          94, name: "Peppermint"                                 },
    Resource { tier:  2, id:         125, name: "Ferns"                                      },
    Resource { tier:  2, id:         127, name: "Pine Weed"                                  },
    Resource { tier:  2, id:         141, name: "Simple Hieroglyphs"                         },
    Resource { tier:  2, id:         176, name: "Collapsed Pillars"                          },
    Resource { tier:  2, id:         179, name: "Vines T2"                                   },
    Resource { tier:  2, id:         180, name: "Root T2"                                    },
    Resource { tier:  2, id:         181, name: "Rubble T2"                                  },
    Resource { tier:  2, id:         190, name: "Key Pedestal"                               },
    Resource { tier:  2, id:         191, name: "Empty Key Pedestal "                        },
    Resource { tier:  2, id:         192, name: "Intricate Door"                             },
    Resource { tier:  2, id:         193, name: "Open Door"                                  },
    Resource { tier:  2, id:         194, name: "Ancient Adventurer's Note"                  },
    Resource { tier:  2, id:     1010008, name: "Planted Birch Sapling"                      },
    Resource { tier:  2, id:     1011008, name: "Planted Birch Tree"                         },
    Resource { tier:  2, id:     1012008, name: "Fully Grown Birch Tree"                     },
    Resource { tier:  2, id:     2011008, name: "Planted Dendro Tree"                        },
    Resource { tier:  2, id:     2012008, name: "Fully Grown Dendro Tree"                    },
    Resource { tier:  2, id:     2020001, name: "Medium Pyrelite Vein"                       },
    Resource { tier:  2, id:     2020002, name: "Large Pyrelite Vein"                        },
    Resource { tier:  2, id:     2050001, name: "Large Garden Boulder"                       },
    Resource { tier:  2, id:     2110000, name: "Driftwood Crayfish"                         },
    Resource { tier:  2, id:     2110001, name: "School Of Emberfin Shiners"                 },
    Resource { tier:  2, id:     2110002, name: "School Of Serpentfish"                      },
    Resource { tier:  2, id:     2110003, name: "Frenzied School Of Serpentfish"             },
    Resource { tier:  2, id:     2110004, name: "Tough Shelled Mussel"                       },
    Resource { tier:  2, id:     2140000, name: "Giant Groundsel Plant"                      },
    Resource { tier:  2, id:   134935169, name: "Pyrelite Vein Interior Depleted"            },
    Resource { tier:  2, id:   464034838, name: "Olivine Sand"                               },
    Resource { tier:  2, id:   699727318, name: "Medium Pyrelite Vein Interior"              },
    Resource { tier:  2, id:   746946997, name: "Hexite Energy Font"                         },
    Resource { tier:  2, id:  1045808810, name: "Pyrelite Outcrop Interior"                  },
    Resource { tier:  2, id:  1619369727, name: "Pyrelite Vein Interior"                     },
    Resource { tier:  2, id:  1673056013, name: "Terrified Adventurer's Note"                },
    Resource { tier:  2, id:  1828992183, name: "Pyrelite Outcrop Interior Depleted"         },
    Resource { tier:  2, id:  1842369948, name: "Medium Pyrelite Vein Interior Depleted"     },
    Resource { tier:  1, id:           1, name: "Sticks"                                     },
    Resource { tier:  1, id:           2, name: "Bush"                                       },
    Resource { tier:  1, id:           3, name: "Rotten Log"                                 },
    Resource { tier:  1, id:           4, name: "Rotten Stump"                               },
    Resource { tier:  1, id:           6, name: "Pine Sapling"                               },
    Resource { tier:  1, id:           7, name: "Spruce Sapling"                             },
    Resource { tier:  1, id:           8, name: "Oak Sapling"                                },
    Resource { tier:  1, id:          10, name: "Beech Sapling"                              },
    Resource { tier:  1, id:          11, name: "Dead Tree"                                  },
    Resource { tier:  1, id:          12, name: "Young Beech Tree"                           },
    Resource { tier:  1, id:          14, name: "Young Oak Tree"                             },
    Resource { tier:  1, id:          19, name: "Mature Beech Tree"                          },
    Resource { tier:  1, id:          21, name: "Mature Oak Tree"                            },
    Resource { tier:  1, id:          38, name: "Flint Pile"                                 },
    Resource { tier:  1, id:          40, name: "Limestone Boulder"                          },
    Resource { tier:  1, id:          41, name: "Limestone Outcrop"                          },
    Resource { tier:  1, id:          42, name: "Large Limestone Outcrop"                    },
    Resource { tier:  1, id:          43, name: "Large Limestone Rock"                       },
    Resource { tier:  1, id:          44, name: "Large Limestone Boulder"                    },
    Resource { tier:  1, id:          45, name: "Limestone Rock Formation"                   },
    Resource { tier:  1, id:          58, name: "Ferralith Vein"                             },
    Resource { tier:  1, id:          59, name: "Ferralith Outcrop"                          },
    Resource { tier:  1, id:          60, name: "Rich Ferralith Vein"                        },
    Resource { tier:  1, id:          66, name: "Mud Mound"                                  },
    Resource { tier:  1, id:          72, name: "Wild Grains"                                },
    Resource { tier:  1, id:          73, name: "Strawberry Bush"                            },
    Resource { tier:  1, id:          74, name: "Button Mushrooms"                           },
    Resource { tier:  1, id:          88, name: "Daisies"                                    },
    Resource { tier:  1, id:          89, name: "Lavender"                                   },
    Resource { tier:  1, id:          90, name: "Lavender Cluster"                           },
    Resource { tier:  1, id:          91, name: "Small Lavender Cluster"                     },
    Resource { tier:  1, id:         140, name: "Rough Hieroglyphs"                          },
    Resource { tier:  1, id:         152, name: "Gem Encrusted Stalagmite"                   },
    Resource { tier:  1, id:         156, name: "Wild Starbulb Plant"                        },
    Resource { tier:  1, id:         158, name: "Salt Deposit"                               },
    Resource { tier:  1, id:         159, name: "Vines"                                      },
    Resource { tier:  1, id:         160, name: "Root"                                       },
    Resource { tier:  1, id:         161, name: "Rubble"                                     },
    Resource { tier:  1, id:         162, name: "Ancient Door"                               },
    Resource { tier:  1, id:         163, name: "Ancient Blue Door"                          },
    Resource { tier:  1, id:         164, name: "Ancient Red Door"                           },
    Resource { tier:  1, id:         165, name: "Ancient Green Door"                         },
    Resource { tier:  1, id:         166, name: "Ancient Yellow Door"                        },
    Resource { tier:  1, id:         167, name: "Complicated Ancient Door"                   },
    Resource { tier:  1, id:         168, name: "Ancient Door "                              },
    Resource { tier:  1, id:         169, name: "Ancient Door   "                            },
    Resource { tier:  1, id:         170, name: "Large Rubble"                               },
    Resource { tier:  1, id:         171, name: "Ancient Brazier"                            },
    Resource { tier:  1, id:         172, name: "Ancient Brazier "                           },
    Resource { tier:  1, id:         173, name: "Lit Ancient Brazier"                        },
    Resource { tier:  1, id:         174, name: "Broken Ancient Brazier"                     },
    Resource { tier:  1, id:         175, name: "Hexite Aurumite Axe"                        },
    Resource { tier:  1, id:         177, name: "Lit Wooden Brazier"                         },
    Resource { tier:  1, id:         178, name: "Wooden Brazier"                             },
    Resource { tier:  1, id:         182, name: "Lit Wooden Brazier "                        },
    Resource { tier:  1, id:         183, name: "Wooden Brazier "                            },
    Resource { tier:  1, id:         184, name: "Collapsed Pillar"                           },
    Resource { tier:  1, id:         185, name: "Ancient Adventurer's Letter"                },
    Resource { tier:  1, id:         186, name: "Ancient Trapsmith's Note"                   },
    Resource { tier:  1, id:         187, name: "Baffled Adventurer's Note"                  },
    Resource { tier:  1, id:         188, name: "Apprehensive Adventurer's Note"             },
    Resource { tier:  1, id:         189, name: "Helpful Adventurer's Note"                  },
    Resource { tier:  1, id:         195, name: "Powered Door"                               },
    Resource { tier:  1, id:         196, name: "Partially Powered Door"                     },
    Resource { tier:  1, id:         197, name: "Unpowered Door"                             },
    Resource { tier:  1, id:         198, name: "Powered Door Contraption"                   },
    Resource { tier:  1, id:         199, name: "Overloaded Door Contraption"                },
    Resource { tier:  1, id:         200, name: "Ornate Door"                                },
    Resource { tier:  1, id:     1010009, name: "Planted Beech Sapling"                      },
    Resource { tier:  1, id:     1010010, name: "Planted Oak Sapling"                        },
    Resource { tier:  1, id:     1011009, name: "Planted Beech Tree"                         },
    Resource { tier:  1, id:     1011010, name: "Planted Oak Tree"                           },
    Resource { tier:  1, id:     1012009, name: "Fully Grown Beech Tree"                     },
    Resource { tier:  1, id:     1012010, name: "Fully Grown Oak Tree"                       },
    Resource { tier:  1, id:     1020001, name: "Medium Ferralith Vein"                      },
    Resource { tier:  1, id:     1090000, name: "Silken Hexmoths"                            },
    Resource { tier:  1, id:     1110000, name: "Moonlit Crawdads"                           },
    Resource { tier:  1, id:     1110001, name: "School Of Breezy Fin Darters "              },
    Resource { tier:  1, id:     1110002, name: "School Of Oceancrest Marlins"               },
    Resource { tier:  1, id:     1110003, name: "Frenzied School Of Oceancrest Marlins"      },
    Resource { tier:  1, id:     1110004, name: "Seaside Clam"                               },
    Resource { tier:  1, id:     2010008, name: "Planted Dendro Sapling"                     },
    Resource { tier:  1, id:     3010009, name: "Planted Pine Sapling"                       },
    Resource { tier:  1, id:     3010010, name: "Planted Spruce Sapling"                     },
    Resource { tier:  1, id:     3010011, name: "Planted Willow Sapling"                     },
    Resource { tier:  1, id:     4010011, name: "Planted Cypress Sapling"                    },
    Resource { tier:  1, id:   152428426, name: "Medium Ferralith Vein Interior Depleted"    },
    Resource { tier:  1, id:   182331452, name: "Traveler's Fruit"                           },
    Resource { tier:  1, id:   204021372, name: "Rough Sand Pile"                            },
    Resource { tier:  1, id:   218270468, name: "Ferralith Outcrop Interior"                 },
    Resource { tier:  1, id:   322711580, name: "Faint Hexite Energy Font"                   },
    Resource { tier:  1, id:   474230316, name: "Ferralith Outcrop Interior Depleted"        },
    Resource { tier:  1, id:   763946195, name: "TEST BirdSpawn"                             },
    Resource { tier:  1, id:  1283632905, name: "Traveler's Fruit (Depleted)"                },
    Resource { tier:  1, id:  1303955933, name: "Traveler's Tree"                            },
    Resource { tier:  1, id:  1435874592, name: "Traveler's Tree (Depleted)"                 },
    Resource { tier:  1, id:  1565420196, name: "Medium Ferralith Vein Interior"             },
    Resource { tier:  1, id:  1917744937, name: "Ferralith Vein Interior Depleted"           },
    Resource { tier:  1, id:  1962517199, name: "Ferralith Vein Interior"                    },
    Resource { tier:  1, id:  2144918116, name: "Daisy"                                      },
    Resource { tier:  0, id:         500, name: "Depleted Sticks"                            },
    Resource { tier:  0, id:         501, name: "Depleted Flint"                             },
    Resource { tier:  0, id:  2145270439, name: "Jakyl Den"                                  },
];